version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "translator"
      POSTGRES_USER: "daniel"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
    restart: unless-stopped